@extends('layouts.app')
@section('title', $department->name)
@section('content')
<div class="space-y-6"><div class="rounded-2xl bg-gradient-to-r from-teal-700 to-blue-700 p-6 text-white"><span class="rounded-full bg-white/15 px-3 py-1 text-xs">KHU VỰC TỔ/NHÓM</span><h1 class="mt-3 text-2xl font-bold">{{ $department->name }}</h1><p class="mt-1 text-teal-50">{{ $department->description }}</p></div>
<div class="grid gap-5 lg:grid-cols-3"><main class="space-y-5 lg:col-span-2"><form method="POST" class="rounded-2xl bg-white p-5 ring-1 ring-slate-200">@csrf<textarea name="content" required rows="3" class="w-full rounded-xl border-slate-300" placeholder="Chia sẻ thông báo với tổ...">{{ old('content') }}</textarea><div class="mt-3 text-right"><button class="rounded-xl bg-blue-600 px-5 py-2 font-semibold text-white">Đăng tin</button></div></form>
<div class="space-y-3">@forelse($posts as $post)<article class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><div class="flex items-center gap-3"><img src="{{ $post->author->avatar_url }}" class="h-10 w-10 rounded-full"><div><b>{{ $post->author }}</b><p class="text-xs text-slate-500">{{ $post->created_at->format('d/m/Y H:i') }}</p></div></div><p class="mt-4 whitespace-pre-line text-slate-700">{{ $post->content }}</p></article>@empty<div class="rounded-2xl bg-white p-10 text-center text-slate-500 ring-1 ring-slate-200">Chưa có bài đăng.</div>@endforelse</div></main>
<aside class="space-y-5"><section class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 class="mb-3 font-semibold">Thành viên ({{ $members->count() }})</h2><div class="space-y-3">@foreach($members as $user)<div class="flex items-center gap-3"><img src="{{ $user->avatar_url }}" class="h-9 w-9 rounded-full"><span class="min-w-0"><b class="block truncate text-sm">{{ $user }}</b><small class="text-slate-500">{{ $department->leader_id===$user->id?'Trưởng tổ':$user->position }}</small></span></div>@endforeach</div></section>
<section class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 class="mb-3 font-semibold">Nhiệm vụ gần đây</h2><div class="space-y-3">@forelse($taskCards as $card)<a href="{{ route(auth()->user()->is_manager ? 'manager_task_detail' : 'staff_task_detail',$card['task']) }}" class="block rounded-xl bg-slate-50 p-3 hover:bg-slate-100"><b class="block text-sm">{{ $card['task']->title }}</b><small class="text-slate-500">{{ $card['status_label'] }} · {{ $card['task']->deadline->format('d/m/Y') }}</small></a>@empty<p class="text-sm text-slate-500">Chưa có nhiệm vụ.</p>@endforelse</div></section></aside></div></div>
@endsection
