# Generated by Django 6.0.7 on 2026-07-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', 'username'], 'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
    ]
