# Generated by Django 6.0.7 on 2026-07-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('ON_LEAVE', 'Nghỉ phép'), ('INACTIVE', 'Ngưng hoạt động')], db_index=True, default='ACTIVE', help_text='ACTIVE=nhận việc bình thường; ON_LEAVE=đăng nhập được nhưng không nhận giao mới; INACTIVE=khóa đăng nhập (đồng bộ is_active=False).', max_length=20, verbose_name='Trạng thái tài khoản'),
        ),
    ]
