@extends('layouts.app')
@section('title', 'Thống kê thi đua')
@section('content')
<div class="space-y-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-2xl font-bold">Thống kê thi đua</h1><p class="text-slate-500">Số lượt Đạt và điểm bị trừ theo kỳ</p></div><a href="{{ route('manager_export_excel',request()->query()) }}" class="rounded-xl bg-emerald-600 px-5 py-2.5 font-semibold text-white">Xuất Excel</a></div>
<form class="grid gap-3 rounded-2xl bg-white p-4 ring-1 ring-slate-200 md:grid-cols-4"><select name="scope" class="rounded-xl border-slate-300"><option value="person" @selected($scope==='person')>Cá nhân</option><option value="department" @selected($scope==='department')>Tổ/Nhóm</option></select><select name="period" id="period" class="rounded-xl border-slate-300"><option value="month" @selected($period==='month')>Theo tháng</option><option value="quarter" @selected($period==='quarter')>Theo quý</option><option value="academic_year" @selected($period==='academic_year')>Theo năm học</option></select><select name="year" class="rounded-xl border-slate-300">@foreach($period==='academic_year'?$academicYears:$years as $y)<option value="{{ $y }}" @selected($year==$y)>{{ $period==='academic_year'?$y.'–'.($y+1):$y }}</option>@endforeach</select><button class="rounded-xl bg-slate-800 text-white">Xem thống kê</button></form>
<div class="overflow-x-auto rounded-2xl bg-white ring-1 ring-slate-200"><table class="min-w-full whitespace-nowrap text-sm"><thead class="sticky top-0 bg-slate-50"><tr><th class="sticky left-0 bg-slate-50 p-3 text-left">{{ $scope==='person'?'Họ tên':'Tổ/Nhóm' }}</th><th class="p-3 text-left">{{ $scope==='person'?'Phòng ban':'Trưởng tổ' }}</th>@foreach($columns as $column)<th class="p-3 text-center">{{ $column }}<span class="block text-[10px] text-slate-400">Đạt / Trừ</span></th>@endforeach<th class="p-3 text-center">Tổng</th></tr></thead><tbody class="divide-y">
@forelse($rows as $row)<tr><td class="sticky left-0 bg-white p-3 font-semibold">{{ $row['label'] }}</td><td class="p-3 text-slate-500">{{ $row['sublabel'] }}</td>@foreach($row['cells'] as $cell)<td class="p-3 text-center"><span class="font-semibold text-emerald-600">{{ $cell['dat_count'] }}</span> / <span class="font-semibold text-rose-600">{{ $cell['penalty_total'] }}</span></td>@endforeach<td class="p-3 text-center font-bold"><span class="text-emerald-600">{{ $row['dat_total'] }}</span> / <span class="text-rose-600">{{ $row['penalty_total'] }}</span></td></tr>@empty<tr><td colspan="{{ count($columns)+3 }}" class="p-10 text-center text-slate-500">Chưa có dữ liệu.</td></tr>@endforelse
</tbody></table></div><p class="text-xs text-slate-500">Kỳ báo cáo: {{ $periodLabel }} · Mỗi ô hiển thị Đạt / Trừ.</p></div>
@endsection
