# Generated by Django 6.0.7 on 2026-07-16 14:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên công việc')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('deadline', models.DateField(verbose_name='Thời hạn')),
                ('cycle', models.CharField(choices=[('month', 'Tháng'), ('quarter', 'Quý'), ('semester', 'Kỳ')], default='month', max_length=20, verbose_name='Chu kỳ')),
                ('base_score', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8, verbose_name='Điểm chuẩn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người giao')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.department', verbose_name='Tổ/Nhóm nhận việc')),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Công việc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'Chưa làm'), ('in_progress', 'Đang làm'), ('pending_review', 'Chờ duyệt'), ('completed', 'Hoàn thành'), ('redo', 'Yêu cầu làm lại')], default='todo', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='proofs/%Y/%m/', verbose_name='File minh chứng')),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Hệ số điểm')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Điểm chốt')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Nhận xét lãnh đạo')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Phân công',
                'verbose_name_plural': 'Phân công',
                'ordering': ['-updated_at'],
                'unique_together': {('task', 'assignee')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_tasks', through='tasks.TaskAssignment', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận'),
        ),
    ]
