# Generated by Django 6.0.7 on 2026-07-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, help_text='Tài liệu hướng dẫn / biểu mẫu kèm theo công việc (tùy chọn).', null=True, upload_to='task_attachments/%Y/%m/', verbose_name='File đính kèm'),
        ),
    ]
