# Generated by Django 6.0.7 on 2026-07-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachment',
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/', verbose_name='File')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Tên file gốc')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Dung lượng (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='Công việc')),
            ],
            options={
                'verbose_name': 'File đính kèm',
                'verbose_name_plural': 'File đính kèm',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
