# Generated by Django 6.0.7 on 2026-07-16 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_attachment_taskattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='target_department',
            new_name='assigned_department',
        ),
        migrations.AddField(
            model_name='task',
            name='delegated_updater',
            field=models.ForeignKey(blank=True, help_text='Thành viên được Trưởng tổ ủy quyền cập nhật tiến độ / upload minh chứng.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_update_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người được ủy quyền cập nhật'),
        ),
        migrations.CreateModel(
            name='TaskParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(choices=[('none', 'Chưa đánh giá'), ('pass', 'Đạt'), ('fail', 'Không đạt')], default='none', max_length=10, verbose_name='Đánh giá nội bộ')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='tasks.task', verbose_name='Công việc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_participations', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên')),
            ],
            options={
                'verbose_name': 'Thành viên tham gia',
                'verbose_name_plural': 'Thành viên tham gia',
                'ordering': ['added_at'],
                'unique_together': {('task', 'user')},
            },
        ),
    ]
