# Generated by Django 6.0.7 on 2026-07-17 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_primary_coordinating_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_subtask',
            field=models.BooleanField(default=False, verbose_name='Là nhiệm vụ con'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Nếu có giá trị thì đây là nhiệm vụ con (sub-task).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='Nhiệm vụ gốc'),
        ),
        migrations.AlterField(
            model_name='task',
            name='delegated_updater',
            field=models.ForeignKey(blank=True, help_text='Thành viên tổ Chủ trì được ủy quyền cập nhật tiến độ / upload minh chứng tổng hợp.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_update_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người được ủy quyền cập nhật'),
        ),
    ]
