# Generated by Django 6.0.7 on 2026-07-17 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_taskassignment_department_target'),
        ('tasks', '0006_task_subtasks_wbs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assignee_department',
            field=models.ForeignKey(blank=True, help_text='Dùng cho giao đồng loạt — Trưởng tổ đại diện cập nhật/nộp minh chứng.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='accounts.department', verbose_name='Tổ/Nhóm nhận việc'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận (cá nhân)'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assignee__isnull', False), ('assignee_department__isnull', True)), models.Q(('assignee__isnull', True), ('assignee_department__isnull', False)), _connector='OR'), name='taskassignment_assignee_xor_department'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('assignee__isnull', False)), fields=('task', 'assignee'), name='uniq_task_assignee_user'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('assignee_department__isnull', False)), fields=('task', 'assignee_department'), name='uniq_task_assignee_department'),
        ),
    ]
