# Generated by Django 6.0.7 on 2026-07-17 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_taskassignment_department_target'),
        ('tasks', '0007_taskassignment_department_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scope_department',
            field=models.ForeignKey(blank=True, help_text='Chỉ dùng cho nhiệm vụ con của luồng giao đồng loạt, để dữ liệu các tổ độc lập.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_subtasks', to='accounts.department', verbose_name='Tổ sở hữu nhiệm vụ con'),
        ),
    ]
