# Generated by Django 6.0.7 on 2026-07-20 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_batch_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='handed_over_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Bàn giao cho'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='handover_status',
            field=models.CharField(choices=[('ACTIVE', 'Đang phụ trách'), ('HANDED_OVER', 'Đã bàn giao')], db_index=True, default='ACTIVE', help_text='ACTIVE=đang phụ trách; HANDED_OVER=đã bàn giao (không còn nhận việc này).', max_length=20, verbose_name='Trạng thái bàn giao'),
        ),
        migrations.AddField(
            model_name='taskparticipation',
            name='handed_over_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_participations', to=settings.AUTH_USER_MODEL, verbose_name='Bàn giao cho'),
        ),
        migrations.AddField(
            model_name='taskparticipation',
            name='handover_status',
            field=models.CharField(choices=[('ACTIVE', 'Đang phụ trách'), ('HANDED_OVER', 'Đã bàn giao')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Trạng thái bàn giao'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_tasks', through='tasks.TaskAssignment', through_fields=('task', 'assignee'), to=settings.AUTH_USER_MODEL, verbose_name='Người nhận'),
        ),
    ]
