# Generated by Django 6.0.7 on 2026-07-20 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_status_and_handover'),
        ('tasks', '0011_account_status_and_handover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='extended_with_penalty',
            field=models.BooleanField(default=False, help_text='True khi người giao gia hạn quá hạn kèm trừ −1.', verbose_name='Đã gia hạn kèm trừ điểm'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='overdue_penalty',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 hoặc 1 — ghi khi gia hạn kèm trừ điểm; không bị ghi đè khi đánh giá.', verbose_name='Điểm trừ do gia hạn quá hạn'),
        ),
        migrations.AddField(
            model_name='taskparticipation',
            name='extended_with_penalty',
            field=models.BooleanField(default=False, help_text='True khi người giao gia hạn quá hạn kèm trừ −1.', verbose_name='Đã gia hạn kèm trừ điểm'),
        ),
        migrations.AddField(
            model_name='taskparticipation',
            name='overdue_penalty',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 hoặc 1 — ghi khi gia hạn kèm trừ điểm; không bị ghi đè khi đánh giá.', verbose_name='Điểm trừ do gia hạn quá hạn'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.CheckConstraint(condition=models.Q(('overdue_penalty__in', [0, 1])), name='taskassignment_overdue_penalty_0_or_1'),
        ),
        migrations.AddConstraint(
            model_name='taskparticipation',
            constraint=models.CheckConstraint(condition=models.Q(('overdue_penalty__in', [0, 1])), name='taskparticipation_overdue_penalty_0_or_1'),
        ),
    ]
